### ISSUE TITLE
How to get the context from events?

### ISSUE THREAD

**Issue by aziz92** [pilwon/node-ib#108]
Perhaps I'm misunderstanding but as far as i can see, there's no way to determine what the context of the events are (what command triggered the event). For example, in the error event:

`.on('error', function (err) {`

how do I know if the error returned is related to me calling, for instance, `placeOrder` command or `reqExecutions` or any other command?

**Comment by danielepolencic** [comment]
The signature is (in Typescript):

```ts
class IB extends EventEmitter {
  on(name: 'error', listener: (err: Error, data: {id: number, code: number}) => void): this
}
```

so the second argument is an object that contains the error code as a number and the id (most of the time this is the id of the order). Now, those are not just error codes, but also _notifications_.

> The TWS uses the IBApi.EWrapper.error method not only to deliver errors but also warnings or informative messages.

Because - you know - mixing error messages and notifications is always a good idea.

You can find a detail list of what this cryptic error messages mean here: https://interactivebrokers.github.io/tws-api/message_codes.html#gsc.tab=0

Funny fact... Some of the error codes **ARE NOT** in that list.

**Comment by nemozny** [comment]
Thanks @danielepolencic ! 
I missed "data" too, but although it doesn't give @aziz92 what he asked for, knowing orderId of a related failed order is (for me) extremely useful.

So simply
```javascript
}).on('error', function (err, data) {
     console.error(err.message);
     console.error(data);
```

@aziz92  no, it is not possible, because TWS doesn't care about the root of the issue (can't blame it), only issues an error code and message.
Here is an overview of error codes, which could broadly categorize your problem.
https://interactivebrokers.github.io/tws-api/message_codes.html
I suggest tracking orderIds (as I do) and then trying to pair the error with the orderId.

You can close this topic.
